env:
  # You may want to update this to whatever the latest version is, or keep it
  # the same as your local machines. However, I have only tested it with 1.8.0+.
  # There should be a time in the future when this is not necessary - it is
  # explained in more detail below.
  DOCKER_COMPOSE_VERSION: 1.18.0

language: java

services:
  - docker

before_script:
  - sudo service mysql stop
  - docker-compose up -d
  - docker ps -a
  - sleep 20 # Wait for deployment

cache:
  directories:
  - $HOME/.m2

script:
  - cd aportes-truchos-api && mvn clean test -B -P dev
  - cd ../aportes-truchos-frontend && mvn clean test -B

# whitelist
branches:
  only:
    - master
