version: '3.3'
services:

  apache:
    image: jmferrer/apache2-reverse-proxy
    container_name: apache
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy:/etc/apache2/sites-enabled
      - /etc/letsencrypt:/etc/apache2/ssl:ro
    depends_on:
      - app
      - api

  api:
    image: tomcat:8-jre8
    container_name: api
    restart: always
    command: ["catalina.sh", "jpda", "run"]
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    ports:
      - 8000:8000
    volumes:
      - ./aportes-truchos-api/webapp:/usr/local/tomcat/webapps/
    depends_on:
      - aportesdb

  app:
    image: tomcat:8-jre8
    container_name: app
    restart: always
    volumes:
      - ./aportes-truchos-frontend/webapp:/usr/local/tomcat/webapps/
    depends_on:
      - api

  aportesdb:
    image: mysql:5.7
    restart: always
    container_name: aportesdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "aportes"
      MYSQL_USER: "usuario"
      MYSQL_PASSWORD: "123ABC123"
      MYSQL_ROOT_PASSWORD: "1A2B3C4E"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./aportes-truchos/aportesdb:/var/lib/mysql
